name: "Run library tests"

on:
  push:
    branches: [main]
    paths: [src/**/*.zig, build.zig, build.zig.zon]
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  test_library:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: goto-bus-stop/setup-zig@v2.0.1
    - run: zig build test -fsummary